#!/bin/sh
# Generate persistent secrets on first run only (never overwrites existing ones).
# SECRET_KEY and JWT_SECRET_KEY are generated by the backend itself into the same
# secrets volume; this script only handles the gluetun control-server API key and
# its auth config, which gluetun needs at boot and cannot generate on its own.
set -e

SECRETS_DIR=/secrets
AUTH_DIR=/gluetun-auth
mkdir -p "$SECRETS_DIR" "$AUTH_DIR"

gen() {
  tr -dc 'A-Za-z0-9' < /dev/urandom | head -c "$1"
}

# gluetun control-server API key (generate once)
if [ ! -f "$SECRETS_DIR/gluetun_api_key" ]; then
  gen 40 > "$SECRETS_DIR/gluetun_api_key"
  echo "bootstrap: generated gluetun control-server API key"
fi

# gluetun control-server auth config using the generated key (generate once)
if [ ! -f "$AUTH_DIR/config.toml" ]; then
  KEY=$(cat "$SECRETS_DIR/gluetun_api_key")
  cat > "$AUTH_DIR/config.toml" <<EOF
[[roles]]
name = "kinora"
routes = [
  "GET /v1/publicip/ip",
  "GET /v1/vpn/status",
  "PUT /v1/vpn/status",
  "GET /v1/vpn/settings",
  "PUT /v1/vpn/settings",
  "GET /v1/openvpn/status",
  "PUT /v1/openvpn/status",
  "GET /v1/openvpn/portforwarded",
  "GET /v1/dns/status",
  "GET /v1/version",
]
auth = "apikey"
apikey = "$KEY"
EOF
  echo "bootstrap: generated gluetun auth config"
fi

echo "bootstrap: complete"
