"""
SQLAlchemy Core table definitions for Alembic migrations.

These are ONLY used for migration generation, not runtime queries.
Runtime queries use raw asyncpg for maximum performance.
"""
from sqlalchemy import (
    MetaData,
    Table,
    Column,
    Integer,
    BigInteger,
    String,
    Text,
    Boolean,
    Float,
    Numeric,
    Date,
    DateTime,
    ForeignKey,
    Index,
    UniqueConstraint,
    ARRAY,
    func,
)
from sqlalchemy.dialects.postgresql import JSONB

# Naming convention for constraints (Alembic needs this for autogenerate)
convention = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}

metadata = MetaData(naming_convention=convention)

# Users and authentication tables
users = Table(
    "users",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("username", String(50), unique=True, nullable=False),
    Column("hashed_password", String(255)),
    Column("is_active", Boolean, default=True, nullable=False),
    Column("last_login_at", DateTime),
    Column("created_at", DateTime, server_default=func.now(), nullable=False),
    Column("updated_at", DateTime, server_default=func.now(), nullable=False),
    Index("idx_users_username", "username"),
)

userAuthProviders = Table(
    "user_auth_providers",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("user_id", Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False),
    Column("provider_type", String(50), nullable=False),
    Column("provider_name", String(100)),
    Column("provider_subject", String(255), nullable=False),
    Column("provider_username", String(255)),
    Column("provider_metadata", JSONB),
    Column("linked_at", DateTime, server_default=func.now(), nullable=False),
    Column("last_used_at", DateTime, server_default=func.now(), nullable=False),
    UniqueConstraint("provider_type", "provider_name", "provider_subject"),
    Index("idx_user_auth_providers_user", "user_id"),
    Index("idx_user_auth_providers_subject", "provider_subject"),
    Index("idx_user_auth_providers_type", "provider_type"),
)

userTotp = Table(
    "user_totp",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("user_id", Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, unique=True),
    Column("secret", String(255), nullable=False),
    Column("enabled", Boolean, default=False, nullable=False),
    Column("backup_codes", JSONB),
    Column("created_at", DateTime, server_default=func.now(), nullable=False),
    Column("verified_at", DateTime),
    Index("idx_user_totp_user", "user_id"),
)

userWebauthnCredentials = Table(
    "user_webauthn_credentials",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("user_id", Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False),
    Column("credential_id", Text, unique=True, nullable=False),
    Column("public_key", Text, nullable=False),
    Column("sign_count", Integer, default=0, nullable=False),
    Column("name", String(100)),
    Column("created_at", DateTime, server_default=func.now(), nullable=False),
    Column("last_used_at", DateTime),
    Index("idx_user_webauthn_user", "user_id"),
    Index("idx_user_webauthn_credential", "credential_id"),
)

# Movies table
movies = Table(
    "movies",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("title", String(255), nullable=False),
    Column("original_title", String(255)),
    Column("overview", Text),
    Column("poster_path", String(500)),
    Column("backdrop_path", String(500)),
    Column("release_date", DateTime),
    Column("genres", JSONB),
    Column("rating", Float),
    Column("vote_count", Integer),
    Column("popularity", Float),
    Column("status", String(50), default="wanted", nullable=False),
    Column("tmdb_id", Integer, unique=True),
    Column("imdb_id", String(20)),
    Column("monitored", Boolean, default=True, nullable=False),
    Column("media_profile_id", Integer),
    Column("root_folder_id", Integer, ForeignKey("root_folders.id", ondelete="SET NULL")),
    Column("runtime", Integer),
    Column("budget", BigInteger),
    Column("revenue", BigInteger),
    Column("tagline", String(500)),
    Column("production_companies", JSONB),
    Column("production_countries", JSONB),
    Column("spoken_languages", JSONB),
    Column("collection_id", Integer),
    Column("collection_name", String(255)),
    Column("has_file", Boolean, default=False, nullable=False),
    Column("file_path", String(1000)),
    Column("file_size", BigInteger),
    Column("quality_detected", String(50)),
    Column("codec", String(50)),
    Column("resolution", String(50)),
    Column("metadata", JSONB),
    Column("upgrade_allowed", Boolean),
    Column("created_at", DateTime, server_default=func.now(), nullable=False),
    Column("updated_at", DateTime, server_default=func.now(), nullable=False),
    Index("idx_movies_tmdb_id", "tmdb_id"),
    Index("idx_movies_imdb_id", "imdb_id"),
    Index("idx_movies_status", "status"),
    Index("idx_movies_monitored", "monitored"),
    Index("idx_movies_collection", "collection_id"),
    Index("idx_movies_media_profile_id", "media_profile_id"),
    Index("idx_movies_status_monitored", "status", "monitored"),
)

# Shows table
shows = Table(
    "shows",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("title", String(255), nullable=False),
    Column("original_title", String(255)),
    Column("overview", Text),
    Column("poster_path", String(500)),
    Column("backdrop_path", String(500)),
    Column("release_date", DateTime),
    Column("genres", JSONB),
    Column("rating", Float),
    Column("vote_count", Integer),
    Column("popularity", Float),
    Column("status", String(50), default="wanted", nullable=False),
    Column("tmdb_id", Integer, unique=True),
    Column("imdb_id", String(20)),
    Column("tvdb_id", Integer),
    Column("tvrage_id", Integer),
    Column("monitored", Boolean, default=True, nullable=False),
    Column("media_profile_id", Integer),
    Column("root_folder_id", Integer, ForeignKey("root_folders.id", ondelete="SET NULL")),
    Column("number_of_seasons", Integer),
    Column("number_of_episodes", Integer),
    Column("episode_run_time", JSONB),
    Column("networks", JSONB),
    Column("production_companies", JSONB),
    Column("first_air_date", DateTime),
    Column("last_air_date", DateTime),
    Column("in_production", Boolean, default=False),
    Column("season_monitoring", String(50), default="all"),
    Column("metadata", JSONB),
    Column("upgrade_allowed", Boolean),
    Column("created_at", DateTime, server_default=func.now(), nullable=False),
    Column("updated_at", DateTime, server_default=func.now(), nullable=False),
    Index("idx_shows_tmdb_id", "tmdb_id"),
    Index("idx_shows_imdb_id", "imdb_id"),
    Index("idx_shows_tvdb_id", "tvdb_id"),
    Index("idx_shows_status", "status"),
    Index("idx_shows_media_profile_id", "media_profile_id"),
    Index("idx_shows_status_monitored", "status", "monitored"),
)

# Seasons table
seasons = Table(
    "seasons",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("show_id", Integer, ForeignKey("shows.id", ondelete="CASCADE"), nullable=False),
    Column("season_number", Integer, nullable=False),
    Column("title", String(500)),
    Column("overview", Text),
    Column("poster_path", String(500)),
    Column("air_date", Date),
    Column("episode_count", Integer),
    Column("monitored", Boolean, default=True, nullable=False),
    Column("created_at", DateTime, server_default=func.now(), nullable=False),
    Column("updated_at", DateTime, server_default=func.now(), nullable=False),
    UniqueConstraint("show_id", "season_number"),
    Index("idx_seasons_show", "show_id"),
    Index("idx_seasons_monitored", "monitored"),
)

# Episodes table
episodes = Table(
    "episodes",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("show_id", Integer, ForeignKey("shows.id", ondelete="CASCADE"), nullable=False),
    Column("season_id", Integer, ForeignKey("seasons.id", ondelete="CASCADE")),
    Column("season_number", Integer, nullable=False),
    Column("episode_number", Integer, nullable=False),
    Column("title", String(500)),
    Column("overview", Text),
    Column("still_path", String(500)),
    Column("air_date", Date),
    Column("runtime", Integer),
    Column("monitored", Boolean, default=True, nullable=False),
    Column("has_file", Boolean, default=False, nullable=False),
    Column("file_path", String(1000)),
    Column("file_size", BigInteger),
    Column("quality_detected", String(50)),
    Column("codec", String(50)),
    Column("resolution", String(50)),
    Column("created_at", DateTime, server_default=func.now(), nullable=False),
    Column("updated_at", DateTime, server_default=func.now(), nullable=False),
    UniqueConstraint("show_id", "season_number", "episode_number"),
    Index("idx_episodes_show", "show_id"),
    Index("idx_episodes_season", "season_id"),
    Index("idx_episodes_monitored", "monitored"),
    Index("idx_episodes_has_file", "has_file"),
)

# Anime table
anime = Table(
    "anime",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("title", String(255), nullable=False),
    Column("original_title", String(255)),
    Column("overview", Text),
    Column("poster_path", String(500)),
    Column("backdrop_path", String(500)),
    Column("release_date", DateTime),
    Column("genres", JSONB),
    Column("rating", Float),
    Column("vote_count", Integer),
    Column("popularity", Float),
    Column("status", String(50), default="wanted", nullable=False),
    Column("tmdb_id", Integer),
    Column("imdb_id", String(20)),
    Column("anilist_id", Integer, unique=True),
    Column("mal_id", Integer),
    Column("monitored", Boolean, default=True, nullable=False),
    Column("media_profile_id", Integer),
    Column("root_folder_id", Integer, ForeignKey("root_folders.id", ondelete="SET NULL")),
    Column("episodes", Integer),
    Column("duration", Integer),
    Column("season_year", Integer),
    Column("season_period", String(50)),
    Column("format", String(50)),
    Column("source", String(50)),
    Column("studios", JSONB),
    Column("is_adult", Boolean, default=False),
    Column("absolute_numbering", Boolean, default=True),
    Column("has_file", Boolean, default=False, nullable=False),
    Column("episode_monitoring", String(50), default="all"),
    Column("metadata", JSONB),
    Column("upgrade_allowed", Boolean),
    Column("created_at", DateTime, server_default=func.now(), nullable=False),
    Column("updated_at", DateTime, server_default=func.now(), nullable=False),
    Index("idx_anime_anilist_id", "anilist_id"),
    Index("idx_anime_mal_id", "mal_id"),
    Index("idx_anime_status", "status"),
    Index("idx_anime_media_profile_id", "media_profile_id"),
    Index("idx_anime_status_monitored", "status", "monitored"),
)

# Anime episodes table
animeEpisodes = Table(
    "anime_episodes",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("anime_id", Integer, ForeignKey("anime.id", ondelete="CASCADE"), nullable=False),
    Column("episode_number", Integer, nullable=False),
    Column("season_number", Integer),
    Column("season_episode", Integer),
    Column("title", String(500)),
    Column("air_date", Date),
    Column("monitored", Boolean, default=True, nullable=False),
    Column("has_file", Boolean, default=False, nullable=False),
    Column("file_path", String(1000)),
    Column("file_size", BigInteger),
    Column("quality_detected", String(50)),
    Column("codec", String(50)),
    Column("resolution", String(50)),
    Column("created_at", DateTime, server_default=func.now(), nullable=False),
    Column("updated_at", DateTime, server_default=func.now(), nullable=False),
    UniqueConstraint("anime_id", "episode_number"),
    Index("idx_anime_episodes_anime", "anime_id"),
    Index("idx_anime_episodes_monitored", "monitored"),
    Index("idx_anime_episodes_has_file", "has_file"),
)

# Artists table
artists = Table(
    "artists",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("name", String(255), nullable=False),
    Column("picture", String(500)),
    Column("picture_medium", String(500)),
    Column("picture_big", String(500)),
    Column("picture_xl", String(500)),
    Column("deezer_id", BigInteger, unique=True),
    Column("monitored", Boolean, default=True, nullable=False),
    Column("root_folder_id", Integer, ForeignKey("root_folders.id", ondelete="SET NULL")),
    Column("genres", JSONB),
    Column("nb_album", Integer),
    Column("nb_fan", Integer),
    Column("has_files", Boolean, default=False, nullable=False),
    Column("created_at", DateTime, server_default=func.now(), nullable=False),
    Column("updated_at", DateTime, server_default=func.now(), nullable=False),
    Index("idx_artists_deezer_id", "deezer_id"),
    Index("idx_artists_monitored", "monitored"),
)

# Albums table
albums = Table(
    "albums",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("title", String(255), nullable=False),
    Column("cover", String(500)),
    Column("cover_medium", String(500)),
    Column("cover_big", String(500)),
    Column("cover_xl", String(500)),
    Column("release_date", DateTime),
    Column("deezer_id", BigInteger, unique=True),
    Column("artist_id", Integer, ForeignKey("artists.id", ondelete="CASCADE")),
    Column("upc", String(50)),
    Column("monitored", Boolean, default=True, nullable=False),
    Column("media_profile_id", Integer),
    Column("root_folder_id", Integer, ForeignKey("root_folders.id", ondelete="SET NULL")),
    Column("status", String(50), default="wanted", nullable=False),
    Column("genres", JSONB),
    Column("nb_tracks", Integer),
    Column("duration", Integer),
    Column("label", String(255)),
    Column("explicit_lyrics", Boolean, default=False),
    Column("record_type", String(50)),
    Column("artist_name", String(255)),
    Column("has_file", Boolean, default=False, nullable=False),
    Column("file_path", String(1000)),
    Column("file_size", BigInteger),
    Column("quality_detected", String(50)),
    Column("codec", String(50)),
    Column("upgrade_allowed", Boolean),
    Column("created_at", DateTime, server_default=func.now(), nullable=False),
    Column("updated_at", DateTime, server_default=func.now(), nullable=False),
    Index("idx_albums_deezer_id", "deezer_id"),
    Index("idx_albums_artist_id", "artist_id"),
    Index("idx_albums_status", "status"),
    Index("idx_albums_monitored", "monitored"),
    Index("idx_albums_media_profile_id", "media_profile_id"),
)

# Tracks table
tracks = Table(
    "tracks",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("title", String(255), nullable=False),
    Column("duration", Integer),
    Column("track_position", Integer),
    Column("disk_number", Integer),
    Column("deezer_id", BigInteger, unique=True),
    Column("album_id", Integer, ForeignKey("albums.id", ondelete="CASCADE")),
    Column("isrc", String(50)),
    Column("explicit_lyrics", Boolean, default=False),
    Column("preview", String(500)),
    Column("artist_name", String(255)),
    Column("album_title", String(255)),
    Column("has_file", Boolean, default=False, nullable=False),
    Column("file_path", String(1000)),
    Column("file_size", BigInteger),
    Column("created_at", DateTime, server_default=func.now(), nullable=False),
    Column("updated_at", DateTime, server_default=func.now(), nullable=False),
    Index("idx_tracks_deezer_id", "deezer_id"),
    Index("idx_tracks_album_id", "album_id"),
    Index("idx_tracks_isrc", "isrc"),
)

# Media profiles table
mediaProfiles = Table(
    "media_profiles",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("name", String(100), unique=True, nullable=False),
    # Movie quality
    Column("movie_resolutions", ARRAY(Text), server_default="{}"),
    Column("movie_codecs", ARRAY(Text), server_default="{}"),
    Column("movie_sources", ARRAY(Text), server_default="{}"),
    Column("movie_audio_codecs", ARRAY(Text), server_default="{}"),
    Column("movie_audio_channels", ARRAY(Text), server_default="{}"),
    Column("movie_hdr_formats", ARRAY(Text), server_default="{}"),
    Column("movie_editions", ARRAY(Text), server_default="{}"),
    Column("movie_min_size", Integer),
    Column("movie_max_size", Integer),
    # Show quality
    Column("show_resolutions", ARRAY(Text), server_default="{}"),
    Column("show_codecs", ARRAY(Text), server_default="{}"),
    Column("show_sources", ARRAY(Text), server_default="{}"),
    Column("show_audio_codecs", ARRAY(Text), server_default="{}"),
    Column("show_audio_channels", ARRAY(Text), server_default="{}"),
    Column("show_hdr_formats", ARRAY(Text), server_default="{}"),
    Column("show_min_size", Integer),
    Column("show_max_size", Integer),
    # Anime quality
    Column("anime_resolutions", ARRAY(Text), server_default="{}"),
    Column("anime_codecs", ARRAY(Text), server_default="{}"),
    Column("anime_sources", ARRAY(Text), server_default="{}"),
    Column("anime_audio_codecs", ARRAY(Text), server_default="{}"),
    Column("anime_audio_channels", ARRAY(Text), server_default="{}"),
    Column("anime_hdr_formats", ARRAY(Text), server_default="{}"),
    Column("anime_min_size", Integer),
    Column("anime_max_size", Integer),
    # Common settings
    Column("languages", ARRAY(Text), server_default="{}"),
    Column("subtitle_languages", ARRAY(Text), server_default="{}"),
    Column("upgrade_allowed", Boolean, default=True),
    Column("uploaders", ARRAY(Text), server_default="{}"),
    Column("release_groups", ARRAY(Text), server_default="{}"),
    Column("regex_filters", ARRAY(Text), server_default="{}"),
    Column("seeder_weight", Integer, default=34),
    Column("size_weight", Integer, default=33),
    Column("recency_weight", Integer, default=33),
    Column("search_sort_preference", String(20), default="weighted"),
    Column("season_pack_preference", String(20), default="prefer"),
    Column("search_timeout", Integer, default=30),
    Column("max_retries", Integer, default=3),
    Column("max_results", Integer, default=100),
    # Minimum seeders required to accept a release
    Column("min_seeds", Integer, server_default="1", nullable=False),
    # Upgrade replace policy: keep_old | delete_old | keep_versions
    Column("upgrade_replace_policy", String(20), server_default="keep_old", nullable=False),
    # Naming formats
    Column("movie_naming_format", Text),
    Column("movie_folder_format", Text),
    Column("show_naming_format", Text),
    Column("show_folder_format", Text),
    Column("anime_naming_format", Text),
    Column("anime_folder_format", Text),
    # Anime options
    Column("anime_subtitle_preference", String(20), default="softsub"),
    Column("anime_allow_hardsub", Boolean, default=False),
    Column("anime_prefer_dual_audio", Boolean, default=False),
    Column("anime_audio_language", String(10), default="ja"),
    Column("anime_subtitle_language", String(10), default="en"),
    # Indexers per media type
    Column("movie_indexers", ARRAY(Text), server_default="{}"),
    Column("show_indexers", ARRAY(Text), server_default="{}"),
    Column("anime_indexers", ARRAY(Text), server_default="{}"),
    Column("music_indexers", ARRAY(Text), server_default="{}"),
    # Music settings
    Column("music_artist_folder_format", Text, default="{artist}"),
    Column("music_album_folder_format", Text, default="{album} ({year})"),
    Column("music_track_naming_format", Text, default="{track:00} - {title}"),
    Column("music_multi_disc_format", Text, default="{disc:00}-{track:00} - {title}"),
    Column("music_preferred_quality", ARRAY(Text), server_default="{'flac','mp3_320','mp3_256','aac'}"),
    Column("music_embed_lyrics", Boolean, default=True),
    Column("music_embed_artwork", Boolean, default=True),
    # File output settings
    Column("media_server", String(20), default="jellyfin"),
    Column("use_hardlinks", Boolean, default=True),
    Column("illegal_char_replacement", String(5), default="_"),
    Column("colon_replacement", String(5), default=" -"),
    # Torrent validation settings
    Column("validation_enabled", Boolean, default=True),
    Column("validation_mode", String(20), server_default="allowlist"),
    Column("forbidden_extensions", ARRAY(Text), server_default="'{.exe,.bat,.cmd,.sh,.msi,.dll,.scr,.com,.ps1,.vbs,.jar}'"),
    Column("validation_failure_action", String(20), default="pause_notify"),
    Column("movie_allowed_extensions", ARRAY(Text), server_default="'{.mkv,.mp4,.avi,.m4v,.mov,.wmv,.flv,.webm,.ts}'"),
    Column("show_allowed_extensions", ARRAY(Text), server_default="'{.mkv,.mp4,.avi,.m4v,.mov,.wmv,.flv,.webm,.ts}'"),
    Column("anime_allowed_extensions", ARRAY(Text), server_default="'{.mkv,.mp4,.avi,.m4v}'"),
    Column("music_allowed_extensions", ARRAY(Text), server_default="'{.flac,.mp3,.m4a,.aac,.ogg,.opus,.wav,.wma}'"),
    # Seeding cascade overrides (NULL = inherit global download-client default)
    Column("seed_ratio_limit", Float),
    Column("seed_time_limit", Integer),
    Column("inactive_seed_time_limit", Integer),
    Column("seed_then_cleanup", Boolean, server_default="false", nullable=False),
    Column("auto_recovery", Boolean),
    Column("created_at", DateTime, server_default=func.now(), nullable=False),
    Column("updated_at", DateTime, server_default=func.now(), nullable=False),
    Index("idx_media_profiles_name", "name"),
)

# App settings table
appSettings = Table(
    "app_settings",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("key", String(100), unique=True, nullable=False),
    Column("value", Text),
    Column("value_type", String(20), default="string", nullable=False),
    Column("is_encrypted", Boolean, default=False, nullable=False),
    Column("category", String(50), nullable=False),
    Column("description", Text),
    Column("created_at", DateTime, server_default=func.now(), nullable=False),
    Column("updated_at", DateTime, server_default=func.now(), nullable=False),
    Index("idx_app_settings_key", "key"),
    Index("idx_app_settings_category", "category"),
)

# Root folders table - stores multiple root folders per media type with paired download paths
rootFolders = Table(
    "root_folders",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("media_type", String(20), nullable=False),
    Column("name", String(100), nullable=False),
    Column("root_path", String(500), nullable=False),
    Column("download_path", String(500), nullable=False),
    Column("priority", Integer, default=0, nullable=False),
    Column("fill_threshold_percent", Integer),
    Column("fill_threshold_gb", Integer),
    Column("is_active", Boolean, default=True, nullable=False),
    Column("is_default", Boolean, default=False, nullable=False),
    Column("total_space_bytes", BigInteger),
    Column("free_space_bytes", BigInteger),
    Column("last_health_check", DateTime),
    Column("health_status", String(20), default="unknown", nullable=False),
    Column("health_message", String(500)),
    Column("created_at", DateTime, server_default=func.now(), nullable=False),
    Column("updated_at", DateTime, server_default=func.now(), nullable=False),
    UniqueConstraint("media_type", "root_path", name="uq_root_folders_media_type_root_path"),
    Index("idx_root_folders_media_type", "media_type"),
)

# Folder selection settings - stores selection mode per media type
folderSelectionSettings = Table(
    "folder_selection_settings",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("media_type", String(20), nullable=False),
    Column("selection_mode", String(20), default="most_free_space", nullable=False),
    Column("created_at", DateTime, server_default=func.now(), nullable=False),
    Column("updated_at", DateTime, server_default=func.now(), nullable=False),
    UniqueConstraint("media_type", name="uq_folder_selection_settings_media_type"),
)

# Download clients table
downloadClients = Table(
    "download_clients",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("name", String(100), nullable=False),
    Column("client_type", String(50), nullable=False),
    Column("host", String(255), nullable=False),
    Column("port", Integer, nullable=False),
    Column("username", String(100)),
    Column("encrypted_password", Text),
    Column("use_ssl", Boolean, default=False, nullable=False),
    Column("is_enabled", Boolean, default=True, nullable=False),
    Column("is_default", Boolean, default=False, nullable=False),
    Column("test_status", String(20), default="untested", nullable=False),
    Column("last_tested", DateTime),
    Column("created_at", DateTime, server_default=func.now(), nullable=False),
    Column("updated_at", DateTime, server_default=func.now(), nullable=False),
    Index("idx_download_clients_enabled", "is_enabled"),
    Index("idx_download_clients_default", "is_default"),
)

# Download history table
downloadHistory = Table(
    "download_history",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("media_id", Integer, nullable=False),
    Column("media_type", String(20), nullable=False),
    Column("torrent_hash", String(100), nullable=False),
    Column("torrent_title", Text, nullable=False),
    Column("indexer", String(50), nullable=False),
    Column("quality", String(50)),
    Column("size", BigInteger),
    Column("status", String(50), default="pending"),
    Column("progress", Float, default=0.0),
    Column("grab_mode", String(20), server_default="auto", nullable=False),
    Column("download_client", String(50)),
    Column("save_path", Text),
    Column("error_message", Text),
    Column("started_at", DateTime, server_default=func.now()),
    Column("completed_at", DateTime),
    Column("episode_id", Integer),
    Column("indexer_page_url", String(2000)),
    Column("torrent_url", String(2000)),
    Column("magnet_link", Text),
    Column("info_hash", String(64)),
    Column("source", String(50)),
    Column("seeders", Integer),
    Column("was_upgrade", Boolean, default=False),
    Column("root_folder_id", Integer, ForeignKey("root_folders.id", ondelete="SET NULL")),
    Column("created_at", DateTime, server_default=func.now(), nullable=False),
    Column("updated_at", DateTime, server_default=func.now(), nullable=False),
    Index("idx_download_history_media", "media_id", "media_type"),
    Index("idx_download_history_hash", "torrent_hash", unique=True),
    Index("idx_download_history_status", "status"),
)

# Blocklist table
blocklist = Table(
    "blocklist",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("media_type", String(50), nullable=False),
    Column("media_id", Integer, nullable=False),
    Column("release_title", String(1000), nullable=False),
    Column("reason", String(500)),
    Column("blocked_at", DateTime, server_default=func.now(), nullable=False),
    Index("idx_blocklist_media", "media_type", "media_id"),
    Index("idx_blocklist_title", "release_title"),
)

# Collections table
collections = Table(
    "collections",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("name", String(255), unique=True, nullable=False),
    Column("description", Text),
    Column("collection_type", String(50)),
    Column("tmdb_collection_id", Integer),
    Column("poster_path", String(500)),
    Column("backdrop_path", String(500)),
    Column("monitored", Boolean, default=True),
    Column("media_profile_id", Integer),
    Column("search_on_add", Boolean, default=True),
    Column("metadata", JSONB),
    Column("created_at", DateTime, server_default=func.now(), nullable=False),
    Column("updated_at", DateTime, server_default=func.now(), nullable=False),
    Index("idx_collections_name", "name"),
    Index("idx_collections_tmdb", "tmdb_collection_id"),
)

# Collection items table
collectionItems = Table(
    "collection_items",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("collection_id", Integer, ForeignKey("collections.id", ondelete="CASCADE")),
    Column("media_id", Integer, nullable=False),
    Column("media_type", String(20), nullable=False),
    Column("sort_order", Integer),
    Column("created_at", DateTime, server_default=func.now(), nullable=False),
    Index("idx_collection_items_collection", "collection_id"),
    Index("idx_collection_items_media", "media_id", "media_type"),
)

# Tags table
tags = Table(
    "tags",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("name", String(100), unique=True, nullable=False),
    Column("color", String(20), default="#6366f1"),
    Column("created_at", DateTime, server_default=func.now(), nullable=False),
    Index("idx_tags_name", "name"),
)

# Media tags junction table
mediaTags = Table(
    "media_tags",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("tag_id", Integer, ForeignKey("tags.id", ondelete="CASCADE"), nullable=False),
    Column("media_type", String(50), nullable=False),
    Column("media_id", Integer, nullable=False),
    Column("created_at", DateTime, server_default=func.now(), nullable=False),
    UniqueConstraint("tag_id", "media_type", "media_id"),
    Index("idx_media_tags_tag", "tag_id"),
    Index("idx_media_tags_media", "media_type", "media_id"),
)

# Transcoding profiles table
transcodingProfiles = Table(
    "transcoding_profiles",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("name", String(100), unique=True, nullable=False),
    Column("description", Text),
    Column("container", String(20)),
    Column("video_codec", String(50)),
    Column("video_quality_mode", String(20)),
    Column("video_quality_value", Integer),
    Column("video_preset", String(50)),
    Column("audio_codec", String(50)),
    Column("audio_bitrate", Integer),
    Column("audio_channels", String(20)),
    Column("resolution", String(20)),
    Column("fps", String(20)),
    Column("hardware_accel_type", String(20)),
    Column("hardware_accel_device", Integer),
    Column("tune", String(50)),
    Column("custom_ffmpeg_args", JSONB),
    Column("is_system", Boolean, default=False),
    Column("created_at", DateTime, server_default=func.now(), nullable=False),
    Column("updated_at", DateTime, server_default=func.now(), nullable=False),
    Index("idx_transcoding_profiles_name", "name"),
)

# Transcoding rules table
transcodingRules = Table(
    "transcoding_rules",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("name", String(100), unique=True, nullable=False),
    Column("enabled", Boolean, default=True),
    Column("priority", Integer, default=0),
    Column("trigger_type", String(50), nullable=False),
    Column("conditions", JSONB),
    Column("profile_id", Integer, ForeignKey("transcoding_profiles.id", ondelete="CASCADE")),
    Column("output_action", String(50), default="replace"),
    Column("use_media_profile_naming", Boolean, default=True),
    Column("media_types", ARRAY(Text), server_default="{'movie','show','anime'}"),
    Column("created_at", DateTime, server_default=func.now(), nullable=False),
    Column("updated_at", DateTime, server_default=func.now(), nullable=False),
    Index("idx_transcoding_rules_enabled", "enabled"),
    Index("idx_transcoding_rules_priority", "priority"),
)

# Transcoding jobs table
transcodingJobs = Table(
    "transcoding_jobs",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("user_id", Integer, ForeignKey("users.id", ondelete="CASCADE")),
    Column("media_id", Integer),
    Column("media_type", String(20)),
    Column("media_title", String(500)),
    Column("input_path", Text, nullable=False),
    Column("output_path", Text),
    Column("output_action", String(50), default="replace"),
    Column("use_media_profile_naming", Boolean, default=True),
    Column("profile_id", Integer, ForeignKey("transcoding_profiles.id", ondelete="SET NULL")),
    Column("profile_snapshot", JSONB, nullable=False),
    Column("hardware_accel_type", String(20)),
    Column("hardware_accel_device", Integer),
    Column("status", String(20), default="pending"),
    Column("progress", Numeric(5, 2), default=0),
    Column("current_frame", Integer),
    Column("total_frames", Integer),
    Column("fps", Numeric(10, 2)),
    Column("speed", String(20)),
    Column("bitrate", String(50)),
    Column("file_size_input", BigInteger),
    Column("file_size_output", BigInteger),
    Column("eta_seconds", Integer),
    Column("celery_task_id", String(255)),
    Column("error_message", Text),
    Column("log_file", Text),
    Column("created_at", DateTime, server_default=func.now(), nullable=False),
    Column("started_at", DateTime),
    Column("completed_at", DateTime),
    Column("updated_at", DateTime, server_default=func.now(), nullable=False),
    Index("idx_transcoding_jobs_status", "status"),
    Index("idx_transcoding_jobs_user", "user_id"),
    Index("idx_transcoding_jobs_media", "media_id", "media_type"),
    Index("idx_transcoding_jobs_created", "created_at"),
)

# Transcoding progress table
transcodingProgress = Table(
    "transcoding_progress",
    metadata,
    Column("job_id", Integer, ForeignKey("transcoding_jobs.id", ondelete="CASCADE"), primary_key=True),
    Column("frame", Integer),
    Column("fps", Numeric(10, 2)),
    Column("bitrate", String(50)),
    Column("size", BigInteger),
    Column("time", String(50)),
    Column("speed", String(20)),
    Column("progress", Numeric(5, 2)),
    Column("updated_at", DateTime, server_default=func.now(), nullable=False),
)

# Hardware acceleration devices table
hardwareAccelDevices = Table(
    "hardware_accel_devices",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("device_type", String(20), nullable=False),
    Column("device_index", Integer, nullable=False),
    Column("device_name", String(255)),
    Column("device_uuid", String(100)),
    Column("pci_bus_id", String(50)),
    Column("compute_capability", String(20)),
    Column("memory_total", BigInteger),
    Column("driver_version", String(50)),
    Column("is_available", Boolean, default=True),
    Column("last_detected", DateTime, server_default=func.now(), nullable=False),
    UniqueConstraint("device_type", "device_index"),
    Index("idx_hardware_accel_type", "device_type"),
    Index("idx_hardware_accel_available", "is_available"),
)

# Permissions table - individual permission definitions
permissions = Table(
    "permissions",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("name", String(100), unique=True, nullable=False),
    Column("display_name", String(100), nullable=False),
    Column("description", Text),
    Column("category", String(50), nullable=False),
    Column("created_at", DateTime, server_default=func.now()),
    Index("idx_permissions_name", "name"),
    Index("idx_permissions_category", "category"),
)

# Permission groups table - named collections of permissions
permissionGroups = Table(
    "permission_groups",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("name", String(100), unique=True, nullable=False),
    Column("display_name", String(100), nullable=False),
    Column("description", Text),
    Column("color", String(7)),
    Column("is_system", Boolean, default=False, nullable=False),
    Column("priority", Integer, default=0, nullable=False),
    Column("created_at", DateTime, server_default=func.now()),
    Column("updated_at", DateTime, server_default=func.now()),
    Index("idx_permission_groups_name", "name"),
    Index("idx_permission_groups_priority", "priority"),
)

# Permission group permissions table - junction between groups and permissions
permissionGroupPermissions = Table(
    "permission_group_permissions",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("group_id", Integer, ForeignKey("permission_groups.id", ondelete="CASCADE"), nullable=False),
    Column("permission_name", String(100), nullable=False),
    UniqueConstraint("group_id", "permission_name"),
    Index("idx_pgp_group", "group_id"),
    Index("idx_pgp_permission", "permission_name"),
)

# User groups table - junction between users and permission groups (stackable)
userGroups = Table(
    "user_groups",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("user_id", Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False),
    Column("group_id", Integer, ForeignKey("permission_groups.id", ondelete="CASCADE"), nullable=False),
    Column("assigned_at", DateTime, server_default=func.now()),
    Column("assigned_by", Integer, ForeignKey("users.id", ondelete="SET NULL")),
    UniqueConstraint("user_id", "group_id"),
    Index("idx_user_groups_user", "user_id"),
    Index("idx_user_groups_group", "group_id"),
)

# Media requests table - pending requests for approval
mediaRequests = Table(
    "media_requests",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("user_id", Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False),
    Column("media_type", String(20), nullable=False),
    Column("external_id", Integer, nullable=False),
    Column("title", String(255), nullable=False),
    Column("poster_path", String(500)),
    Column("year", Integer),
    Column("overview", Text),
    Column("metadata", JSONB),
    Column("status", String(20), default="pending", nullable=False),
    Column("requested_at", DateTime, server_default=func.now()),
    Column("reviewed_at", DateTime),
    Column("reviewed_by", Integer, ForeignKey("users.id", ondelete="SET NULL")),
    Column("review_notes", Text),
    Column("request_notes", Text),
    Column("media_profile_id", Integer),
    Column("root_folder_id", Integer, ForeignKey("root_folders.id", ondelete="SET NULL")),
    Column("auto_search", Boolean, default=True),
    Column("created_media_id", Integer),
    Index("idx_media_requests_user", "user_id"),
    Index("idx_media_requests_status", "status"),
    Index("idx_media_requests_media_type", "media_type"),
    Index("idx_media_requests_external", "media_type", "external_id"),
)
