"""initial_schema

Revision ID: c576e9cecf58
Revises: 
Create Date: 2025-12-21 20:23:58.233560+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# Revision identifiers, used by Alembic.
revision: str = 'c576e9cecf58'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anime',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('original_title', sa.String(length=255), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('poster_path', sa.String(length=500), nullable=True),
    sa.Column('backdrop_path', sa.String(length=500), nullable=True),
    sa.Column('release_date', sa.DateTime(), nullable=True),
    sa.Column('genres', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('vote_count', sa.Integer(), nullable=True),
    sa.Column('popularity', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=True),
    sa.Column('imdb_id', sa.String(length=20), nullable=True),
    sa.Column('anilist_id', sa.Integer(), nullable=True),
    sa.Column('mal_id', sa.Integer(), nullable=True),
    sa.Column('monitored', sa.Boolean(), nullable=False),
    sa.Column('media_profile_id', sa.Integer(), nullable=True),
    sa.Column('root_folder_path', sa.String(length=500), nullable=True),
    sa.Column('episodes', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('season_year', sa.Integer(), nullable=True),
    sa.Column('season_period', sa.String(length=50), nullable=True),
    sa.Column('format', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('studios', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_adult', sa.Boolean(), nullable=True),
    sa.Column('absolute_numbering', sa.Boolean(), nullable=True),
    sa.Column('has_file', sa.Boolean(), nullable=False),
    sa.Column('episode_monitoring', sa.String(length=50), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('upgrade_allowed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_anime')),
    sa.UniqueConstraint('anilist_id', name=op.f('uq_anime_anilist_id'))
    )
    op.create_index('idx_anime_anilist_id', 'anime', ['anilist_id'], unique=False)
    op.create_index('idx_anime_mal_id', 'anime', ['mal_id'], unique=False)
    op.create_index('idx_anime_media_profile_id', 'anime', ['media_profile_id'], unique=False)
    op.create_index('idx_anime_status', 'anime', ['status'], unique=False)
    op.create_index('idx_anime_status_monitored', 'anime', ['status', 'monitored'], unique=False)
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('value_type', sa.String(length=20), nullable=False),
    sa.Column('is_encrypted', sa.Boolean(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_settings')),
    sa.UniqueConstraint('key', name=op.f('uq_app_settings_key'))
    )
    op.create_index('idx_app_settings_category', 'app_settings', ['category'], unique=False)
    op.create_index('idx_app_settings_key', 'app_settings', ['key'], unique=False)
    op.create_table('artists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('picture', sa.String(length=500), nullable=True),
    sa.Column('picture_medium', sa.String(length=500), nullable=True),
    sa.Column('picture_big', sa.String(length=500), nullable=True),
    sa.Column('picture_xl', sa.String(length=500), nullable=True),
    sa.Column('deezer_id', sa.BigInteger(), nullable=True),
    sa.Column('monitored', sa.Boolean(), nullable=False),
    sa.Column('root_folder_path', sa.String(length=500), nullable=True),
    sa.Column('genres', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('nb_album', sa.Integer(), nullable=True),
    sa.Column('nb_fan', sa.Integer(), nullable=True),
    sa.Column('has_files', sa.Boolean(), nullable=False),
    sa.Column('upgrade_allowed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artists')),
    sa.UniqueConstraint('deezer_id', name=op.f('uq_artists_deezer_id'))
    )
    op.create_index('idx_artists_deezer_id', 'artists', ['deezer_id'], unique=False)
    op.create_index('idx_artists_monitored', 'artists', ['monitored'], unique=False)
    op.create_table('blocklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.String(length=50), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('release_title', sa.String(length=1000), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('blocked_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blocklist'))
    )
    op.create_index('idx_blocklist_media', 'blocklist', ['media_type', 'media_id'], unique=False)
    op.create_index('idx_blocklist_title', 'blocklist', ['release_title'], unique=False)
    op.create_table('collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('collection_type', sa.String(length=50), nullable=True),
    sa.Column('tmdb_collection_id', sa.Integer(), nullable=True),
    sa.Column('poster_path', sa.String(length=500), nullable=True),
    sa.Column('backdrop_path', sa.String(length=500), nullable=True),
    sa.Column('monitored', sa.Boolean(), nullable=True),
    sa.Column('media_profile_id', sa.Integer(), nullable=True),
    sa.Column('search_on_add', sa.Boolean(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collections')),
    sa.UniqueConstraint('name', name=op.f('uq_collections_name'))
    )
    op.create_index('idx_collections_name', 'collections', ['name'], unique=False)
    op.create_index('idx_collections_tmdb', 'collections', ['tmdb_collection_id'], unique=False)
    op.create_table('download_clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('client_type', sa.String(length=50), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('encrypted_password', sa.Text(), nullable=True),
    sa.Column('use_ssl', sa.Boolean(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('test_status', sa.String(length=20), nullable=False),
    sa.Column('last_tested', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_download_clients'))
    )
    op.create_index('idx_download_clients_default', 'download_clients', ['is_default'], unique=False)
    op.create_index('idx_download_clients_enabled', 'download_clients', ['is_enabled'], unique=False)
    op.create_table('download_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.String(length=20), nullable=False),
    sa.Column('torrent_hash', sa.String(length=100), nullable=False),
    sa.Column('torrent_title', sa.Text(), nullable=False),
    sa.Column('indexer', sa.String(length=50), nullable=False),
    sa.Column('quality', sa.String(length=50), nullable=True),
    sa.Column('size', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('download_client', sa.String(length=50), nullable=True),
    sa.Column('save_path', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('episode_id', sa.Integer(), nullable=True),
    sa.Column('indexer_page_url', sa.String(length=2000), nullable=True),
    sa.Column('torrent_url', sa.String(length=2000), nullable=True),
    sa.Column('magnet_link', sa.Text(), nullable=True),
    sa.Column('info_hash', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('seeders', sa.Integer(), nullable=True),
    sa.Column('was_upgrade', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_download_history'))
    )
    op.create_index('idx_download_history_hash', 'download_history', ['torrent_hash'], unique=False)
    op.create_index('idx_download_history_media', 'download_history', ['media_id', 'media_type'], unique=False)
    op.create_index('idx_download_history_status', 'download_history', ['status'], unique=False)
    op.create_table('hardware_accel_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_type', sa.String(length=20), nullable=False),
    sa.Column('device_index', sa.Integer(), nullable=False),
    sa.Column('device_name', sa.String(length=255), nullable=True),
    sa.Column('device_uuid', sa.String(length=100), nullable=True),
    sa.Column('pci_bus_id', sa.String(length=50), nullable=True),
    sa.Column('compute_capability', sa.String(length=20), nullable=True),
    sa.Column('memory_total', sa.BigInteger(), nullable=True),
    sa.Column('driver_version', sa.String(length=50), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('last_detected', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hardware_accel_devices')),
    sa.UniqueConstraint('device_type', 'device_index', name=op.f('uq_hardware_accel_devices_device_type'))
    )
    op.create_index('idx_hardware_accel_available', 'hardware_accel_devices', ['is_available'], unique=False)
    op.create_index('idx_hardware_accel_type', 'hardware_accel_devices', ['device_type'], unique=False)
    op.create_table('media_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('min_size', sa.Integer(), nullable=True),
    sa.Column('max_size', sa.Integer(), nullable=True),
    sa.Column('resolutions', sa.ARRAY(sa.Text()), server_default='{}', nullable=True),
    sa.Column('codecs', sa.ARRAY(sa.Text()), server_default='{}', nullable=True),
    sa.Column('sources', sa.ARRAY(sa.Text()), server_default='{}', nullable=True),
    sa.Column('audio_codecs', sa.ARRAY(sa.Text()), server_default='{}', nullable=True),
    sa.Column('audio_channels', sa.ARRAY(sa.Text()), server_default='{}', nullable=True),
    sa.Column('hdr_formats', sa.ARRAY(sa.Text()), server_default='{}', nullable=True),
    sa.Column('editions', sa.ARRAY(sa.Text()), server_default='{}', nullable=True),
    sa.Column('movie_resolutions', sa.ARRAY(sa.Text()), server_default='{}', nullable=True),
    sa.Column('movie_codecs', sa.ARRAY(sa.Text()), server_default='{}', nullable=True),
    sa.Column('movie_sources', sa.ARRAY(sa.Text()), server_default='{}', nullable=True),
    sa.Column('movie_audio_codecs', sa.ARRAY(sa.Text()), server_default='{}', nullable=True),
    sa.Column('movie_audio_channels', sa.ARRAY(sa.Text()), server_default='{}', nullable=True),
    sa.Column('movie_hdr_formats', sa.ARRAY(sa.Text()), server_default='{}', nullable=True),
    sa.Column('movie_editions', sa.ARRAY(sa.Text()), server_default='{}', nullable=True),
    sa.Column('movie_min_size', sa.Integer(), nullable=True),
    sa.Column('movie_max_size', sa.Integer(), nullable=True),
    sa.Column('show_resolutions', sa.ARRAY(sa.Text()), server_default='{}', nullable=True),
    sa.Column('show_codecs', sa.ARRAY(sa.Text()), server_default='{}', nullable=True),
    sa.Column('show_sources', sa.ARRAY(sa.Text()), server_default='{}', nullable=True),
    sa.Column('show_audio_codecs', sa.ARRAY(sa.Text()), server_default='{}', nullable=True),
    sa.Column('show_audio_channels', sa.ARRAY(sa.Text()), server_default='{}', nullable=True),
    sa.Column('show_hdr_formats', sa.ARRAY(sa.Text()), server_default='{}', nullable=True),
    sa.Column('show_min_size', sa.Integer(), nullable=True),
    sa.Column('show_max_size', sa.Integer(), nullable=True),
    sa.Column('anime_resolutions', sa.ARRAY(sa.Text()), server_default='{}', nullable=True),
    sa.Column('anime_codecs', sa.ARRAY(sa.Text()), server_default='{}', nullable=True),
    sa.Column('anime_sources', sa.ARRAY(sa.Text()), server_default='{}', nullable=True),
    sa.Column('anime_audio_codecs', sa.ARRAY(sa.Text()), server_default='{}', nullable=True),
    sa.Column('anime_audio_channels', sa.ARRAY(sa.Text()), server_default='{}', nullable=True),
    sa.Column('anime_hdr_formats', sa.ARRAY(sa.Text()), server_default='{}', nullable=True),
    sa.Column('anime_min_size', sa.Integer(), nullable=True),
    sa.Column('anime_max_size', sa.Integer(), nullable=True),
    sa.Column('languages', sa.ARRAY(sa.Text()), server_default='{}', nullable=True),
    sa.Column('subtitle_languages', sa.ARRAY(sa.Text()), server_default='{}', nullable=True),
    sa.Column('upgrade_allowed', sa.Boolean(), nullable=True),
    sa.Column('indexers', sa.ARRAY(sa.Text()), server_default='{}', nullable=True),
    sa.Column('uploaders', sa.ARRAY(sa.Text()), server_default='{}', nullable=True),
    sa.Column('release_groups', sa.ARRAY(sa.Text()), server_default='{}', nullable=True),
    sa.Column('regex_filters', sa.ARRAY(sa.Text()), server_default='{}', nullable=True),
    sa.Column('seeder_weight', sa.Integer(), nullable=True),
    sa.Column('size_weight', sa.Integer(), nullable=True),
    sa.Column('recency_weight', sa.Integer(), nullable=True),
    sa.Column('search_sort_preference', sa.String(length=20), nullable=True),
    sa.Column('season_pack_preference', sa.String(length=20), nullable=True),
    sa.Column('search_timeout', sa.Integer(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('max_results', sa.Integer(), nullable=True),
    sa.Column('movie_naming_format', sa.Text(), nullable=True),
    sa.Column('movie_folder_format', sa.Text(), nullable=True),
    sa.Column('show_naming_format', sa.Text(), nullable=True),
    sa.Column('show_folder_format', sa.Text(), nullable=True),
    sa.Column('anime_naming_format', sa.Text(), nullable=True),
    sa.Column('anime_folder_format', sa.Text(), nullable=True),
    sa.Column('anime_subtitle_preference', sa.String(length=20), nullable=True),
    sa.Column('anime_allow_hardsub', sa.Boolean(), nullable=True),
    sa.Column('anime_prefer_dual_audio', sa.Boolean(), nullable=True),
    sa.Column('anime_audio_language', sa.String(length=10), nullable=True),
    sa.Column('anime_subtitle_language', sa.String(length=10), nullable=True),
    sa.Column('movie_indexers', sa.ARRAY(sa.Text()), server_default='{}', nullable=True),
    sa.Column('show_indexers', sa.ARRAY(sa.Text()), server_default='{}', nullable=True),
    sa.Column('anime_indexers', sa.ARRAY(sa.Text()), server_default='{}', nullable=True),
    sa.Column('music_indexers', sa.ARRAY(sa.Text()), server_default='{}', nullable=True),
    sa.Column('music_artist_folder_format', sa.Text(), nullable=True),
    sa.Column('music_album_folder_format', sa.Text(), nullable=True),
    sa.Column('music_track_naming_format', sa.Text(), nullable=True),
    sa.Column('music_multi_disc_format', sa.Text(), nullable=True),
    sa.Column('music_preferred_quality', sa.ARRAY(sa.Text()), server_default="{'flac','mp3_320','mp3_256','aac'}", nullable=True),
    sa.Column('music_embed_lyrics', sa.Boolean(), nullable=True),
    sa.Column('music_embed_artwork', sa.Boolean(), nullable=True),
    sa.Column('media_server', sa.String(length=20), nullable=True),
    sa.Column('use_hardlinks', sa.Boolean(), nullable=True),
    sa.Column('illegal_char_replacement', sa.String(length=5), nullable=True),
    sa.Column('colon_replacement', sa.String(length=5), nullable=True),
    sa.Column('validation_enabled', sa.Boolean(), nullable=True),
    sa.Column('allowed_extensions', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('forbidden_extensions', sa.ARRAY(sa.Text()), server_default='{.exe,.bat,.cmd,.sh,.msi,.dll,.scr,.com,.ps1,.vbs,.jar}', nullable=True),
    sa.Column('validation_failure_action', sa.String(length=20), nullable=True),
    sa.Column('movie_allowed_extensions', sa.ARRAY(sa.Text()), server_default='{.mkv,.mp4,.avi,.m4v,.mov,.wmv,.flv,.webm,.ts}', nullable=True),
    sa.Column('show_allowed_extensions', sa.ARRAY(sa.Text()), server_default='{.mkv,.mp4,.avi,.m4v,.mov,.wmv,.flv,.webm,.ts}', nullable=True),
    sa.Column('anime_allowed_extensions', sa.ARRAY(sa.Text()), server_default='{.mkv,.mp4,.avi,.m4v}', nullable=True),
    sa.Column('music_allowed_extensions', sa.ARRAY(sa.Text()), server_default='{.flac,.mp3,.m4a,.aac,.ogg,.opus,.wav,.wma}', nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_profiles')),
    sa.UniqueConstraint('name', name=op.f('uq_media_profiles_name'))
    )
    op.create_index('idx_media_profiles_name', 'media_profiles', ['name'], unique=False)
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('original_title', sa.String(length=255), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('poster_path', sa.String(length=500), nullable=True),
    sa.Column('backdrop_path', sa.String(length=500), nullable=True),
    sa.Column('release_date', sa.DateTime(), nullable=True),
    sa.Column('genres', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('vote_count', sa.Integer(), nullable=True),
    sa.Column('popularity', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=True),
    sa.Column('imdb_id', sa.String(length=20), nullable=True),
    sa.Column('monitored', sa.Boolean(), nullable=False),
    sa.Column('media_profile_id', sa.Integer(), nullable=True),
    sa.Column('root_folder_path', sa.String(length=500), nullable=True),
    sa.Column('runtime', sa.Integer(), nullable=True),
    sa.Column('budget', sa.BigInteger(), nullable=True),
    sa.Column('revenue', sa.BigInteger(), nullable=True),
    sa.Column('tagline', sa.String(length=500), nullable=True),
    sa.Column('production_companies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('production_countries', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('spoken_languages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.Column('collection_name', sa.String(length=255), nullable=True),
    sa.Column('has_file', sa.Boolean(), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('quality_detected', sa.String(length=50), nullable=True),
    sa.Column('codec', sa.String(length=50), nullable=True),
    sa.Column('resolution', sa.String(length=50), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('upgrade_allowed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_movies')),
    sa.UniqueConstraint('tmdb_id', name=op.f('uq_movies_tmdb_id'))
    )
    op.create_index('idx_movies_collection', 'movies', ['collection_id'], unique=False)
    op.create_index('idx_movies_imdb_id', 'movies', ['imdb_id'], unique=False)
    op.create_index('idx_movies_media_profile_id', 'movies', ['media_profile_id'], unique=False)
    op.create_index('idx_movies_monitored', 'movies', ['monitored'], unique=False)
    op.create_index('idx_movies_status', 'movies', ['status'], unique=False)
    op.create_index('idx_movies_status_monitored', 'movies', ['status', 'monitored'], unique=False)
    op.create_index('idx_movies_tmdb_id', 'movies', ['tmdb_id'], unique=False)
    op.create_table('shows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('original_title', sa.String(length=255), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('poster_path', sa.String(length=500), nullable=True),
    sa.Column('backdrop_path', sa.String(length=500), nullable=True),
    sa.Column('release_date', sa.DateTime(), nullable=True),
    sa.Column('genres', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('vote_count', sa.Integer(), nullable=True),
    sa.Column('popularity', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=True),
    sa.Column('imdb_id', sa.String(length=20), nullable=True),
    sa.Column('tvdb_id', sa.Integer(), nullable=True),
    sa.Column('tvrage_id', sa.Integer(), nullable=True),
    sa.Column('monitored', sa.Boolean(), nullable=False),
    sa.Column('media_profile_id', sa.Integer(), nullable=True),
    sa.Column('root_folder_path', sa.String(length=500), nullable=True),
    sa.Column('number_of_seasons', sa.Integer(), nullable=True),
    sa.Column('number_of_episodes', sa.Integer(), nullable=True),
    sa.Column('episode_run_time', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('networks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('production_companies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('first_air_date', sa.DateTime(), nullable=True),
    sa.Column('last_air_date', sa.DateTime(), nullable=True),
    sa.Column('in_production', sa.Boolean(), nullable=True),
    sa.Column('season_monitoring', sa.String(length=50), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('upgrade_allowed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shows')),
    sa.UniqueConstraint('tmdb_id', name=op.f('uq_shows_tmdb_id'))
    )
    op.create_index('idx_shows_imdb_id', 'shows', ['imdb_id'], unique=False)
    op.create_index('idx_shows_media_profile_id', 'shows', ['media_profile_id'], unique=False)
    op.create_index('idx_shows_status', 'shows', ['status'], unique=False)
    op.create_index('idx_shows_status_monitored', 'shows', ['status', 'monitored'], unique=False)
    op.create_index('idx_shows_tmdb_id', 'shows', ['tmdb_id'], unique=False)
    op.create_index('idx_shows_tvdb_id', 'shows', ['tvdb_id'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags')),
    sa.UniqueConstraint('name', name=op.f('uq_tags_name'))
    )
    op.create_index('idx_tags_name', 'tags', ['name'], unique=False)
    op.create_table('transcoding_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('container', sa.String(length=20), nullable=True),
    sa.Column('video_codec', sa.String(length=50), nullable=True),
    sa.Column('video_quality_mode', sa.String(length=20), nullable=True),
    sa.Column('video_quality_value', sa.Integer(), nullable=True),
    sa.Column('video_preset', sa.String(length=50), nullable=True),
    sa.Column('audio_codec', sa.String(length=50), nullable=True),
    sa.Column('audio_bitrate', sa.Integer(), nullable=True),
    sa.Column('audio_channels', sa.String(length=20), nullable=True),
    sa.Column('resolution', sa.String(length=20), nullable=True),
    sa.Column('fps', sa.String(length=20), nullable=True),
    sa.Column('hardware_accel_type', sa.String(length=20), nullable=True),
    sa.Column('hardware_accel_device', sa.Integer(), nullable=True),
    sa.Column('tune', sa.String(length=50), nullable=True),
    sa.Column('custom_ffmpeg_args', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transcoding_profiles')),
    sa.UniqueConstraint('name', name=op.f('uq_transcoding_profiles_name'))
    )
    op.create_index('idx_transcoding_profiles_name', 'transcoding_profiles', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_index('idx_users_role', 'users', ['role'], unique=False)
    op.create_index('idx_users_username', 'users', ['username'], unique=False)
    op.create_table('albums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('cover', sa.String(length=500), nullable=True),
    sa.Column('cover_medium', sa.String(length=500), nullable=True),
    sa.Column('cover_big', sa.String(length=500), nullable=True),
    sa.Column('cover_xl', sa.String(length=500), nullable=True),
    sa.Column('release_date', sa.DateTime(), nullable=True),
    sa.Column('deezer_id', sa.BigInteger(), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('upc', sa.String(length=50), nullable=True),
    sa.Column('monitored', sa.Boolean(), nullable=False),
    sa.Column('media_profile_id', sa.Integer(), nullable=True),
    sa.Column('root_folder_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('genres', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('nb_tracks', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('explicit_lyrics', sa.Boolean(), nullable=True),
    sa.Column('record_type', sa.String(length=50), nullable=True),
    sa.Column('artist_name', sa.String(length=255), nullable=True),
    sa.Column('has_file', sa.Boolean(), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('quality_detected', sa.String(length=50), nullable=True),
    sa.Column('codec', sa.String(length=50), nullable=True),
    sa.Column('upgrade_allowed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], name=op.f('fk_albums_artist_id_artists'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_albums')),
    sa.UniqueConstraint('deezer_id', name=op.f('uq_albums_deezer_id'))
    )
    op.create_index('idx_albums_artist_id', 'albums', ['artist_id'], unique=False)
    op.create_index('idx_albums_deezer_id', 'albums', ['deezer_id'], unique=False)
    op.create_index('idx_albums_media_profile_id', 'albums', ['media_profile_id'], unique=False)
    op.create_index('idx_albums_monitored', 'albums', ['monitored'], unique=False)
    op.create_index('idx_albums_status', 'albums', ['status'], unique=False)
    op.create_table('anime_episodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.Column('episode_number', sa.Integer(), nullable=False),
    sa.Column('season_number', sa.Integer(), nullable=True),
    sa.Column('season_episode', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('air_date', sa.Date(), nullable=True),
    sa.Column('monitored', sa.Boolean(), nullable=False),
    sa.Column('has_file', sa.Boolean(), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('quality_detected', sa.String(length=50), nullable=True),
    sa.Column('codec', sa.String(length=50), nullable=True),
    sa.Column('resolution', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['anime_id'], ['anime.id'], name=op.f('fk_anime_episodes_anime_id_anime'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_anime_episodes')),
    sa.UniqueConstraint('anime_id', 'episode_number', name=op.f('uq_anime_episodes_anime_id'))
    )
    op.create_index('idx_anime_episodes_anime', 'anime_episodes', ['anime_id'], unique=False)
    op.create_index('idx_anime_episodes_has_file', 'anime_episodes', ['has_file'], unique=False)
    op.create_index('idx_anime_episodes_monitored', 'anime_episodes', ['monitored'], unique=False)
    op.create_table('collection_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.String(length=20), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], name=op.f('fk_collection_items_collection_id_collections'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collection_items'))
    )
    op.create_index('idx_collection_items_collection', 'collection_items', ['collection_id'], unique=False)
    op.create_index('idx_collection_items_media', 'collection_items', ['media_id', 'media_type'], unique=False)
    op.create_table('media_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.String(length=50), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_media_tags_tag_id_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_tags')),
    sa.UniqueConstraint('tag_id', 'media_type', 'media_id', name=op.f('uq_media_tags_tag_id'))
    )
    op.create_index('idx_media_tags_media', 'media_tags', ['media_type', 'media_id'], unique=False)
    op.create_index('idx_media_tags_tag', 'media_tags', ['tag_id'], unique=False)
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('show_id', sa.Integer(), nullable=False),
    sa.Column('season_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('poster_path', sa.String(length=500), nullable=True),
    sa.Column('air_date', sa.Date(), nullable=True),
    sa.Column('episode_count', sa.Integer(), nullable=True),
    sa.Column('monitored', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], name=op.f('fk_seasons_show_id_shows'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seasons')),
    sa.UniqueConstraint('show_id', 'season_number', name=op.f('uq_seasons_show_id'))
    )
    op.create_index('idx_seasons_monitored', 'seasons', ['monitored'], unique=False)
    op.create_index('idx_seasons_show', 'seasons', ['show_id'], unique=False)
    op.create_table('transcoding_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('media_id', sa.Integer(), nullable=True),
    sa.Column('media_type', sa.String(length=20), nullable=True),
    sa.Column('media_title', sa.String(length=500), nullable=True),
    sa.Column('input_path', sa.Text(), nullable=False),
    sa.Column('output_path', sa.Text(), nullable=True),
    sa.Column('output_action', sa.String(length=50), nullable=True),
    sa.Column('use_media_profile_naming', sa.Boolean(), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('profile_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('hardware_accel_type', sa.String(length=20), nullable=True),
    sa.Column('hardware_accel_device', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('progress', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('current_frame', sa.Integer(), nullable=True),
    sa.Column('total_frames', sa.Integer(), nullable=True),
    sa.Column('fps', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('speed', sa.String(length=20), nullable=True),
    sa.Column('bitrate', sa.String(length=50), nullable=True),
    sa.Column('file_size_input', sa.BigInteger(), nullable=True),
    sa.Column('file_size_output', sa.BigInteger(), nullable=True),
    sa.Column('eta_seconds', sa.Integer(), nullable=True),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('log_file', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['transcoding_profiles.id'], name=op.f('fk_transcoding_jobs_profile_id_transcoding_profiles'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_transcoding_jobs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transcoding_jobs'))
    )
    op.create_index('idx_transcoding_jobs_created', 'transcoding_jobs', ['created_at'], unique=False)
    op.create_index('idx_transcoding_jobs_media', 'transcoding_jobs', ['media_id', 'media_type'], unique=False)
    op.create_index('idx_transcoding_jobs_status', 'transcoding_jobs', ['status'], unique=False)
    op.create_index('idx_transcoding_jobs_user', 'transcoding_jobs', ['user_id'], unique=False)
    op.create_table('transcoding_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('trigger_type', sa.String(length=50), nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('output_action', sa.String(length=50), nullable=True),
    sa.Column('use_media_profile_naming', sa.Boolean(), nullable=True),
    sa.Column('media_types', sa.ARRAY(sa.Text()), server_default="{'movie','show','anime'}", nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['transcoding_profiles.id'], name=op.f('fk_transcoding_rules_profile_id_transcoding_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transcoding_rules')),
    sa.UniqueConstraint('name', name=op.f('uq_transcoding_rules_name'))
    )
    op.create_index('idx_transcoding_rules_enabled', 'transcoding_rules', ['enabled'], unique=False)
    op.create_index('idx_transcoding_rules_priority', 'transcoding_rules', ['priority'], unique=False)
    op.create_table('user_auth_providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider_type', sa.String(length=50), nullable=False),
    sa.Column('provider_name', sa.String(length=100), nullable=True),
    sa.Column('provider_subject', sa.String(length=255), nullable=False),
    sa.Column('provider_username', sa.String(length=255), nullable=True),
    sa.Column('provider_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('linked_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_auth_providers_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_auth_providers')),
    sa.UniqueConstraint('provider_type', 'provider_name', 'provider_subject', name=op.f('uq_user_auth_providers_provider_type'))
    )
    op.create_index('idx_user_auth_providers_subject', 'user_auth_providers', ['provider_subject'], unique=False)
    op.create_index('idx_user_auth_providers_type', 'user_auth_providers', ['provider_type'], unique=False)
    op.create_index('idx_user_auth_providers_user', 'user_auth_providers', ['user_id'], unique=False)
    op.create_table('user_totp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('secret', sa.String(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('backup_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_totp_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_totp')),
    sa.UniqueConstraint('user_id', name=op.f('uq_user_totp_user_id'))
    )
    op.create_index('idx_user_totp_user', 'user_totp', ['user_id'], unique=False)
    op.create_table('user_webauthn_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('credential_id', sa.Text(), nullable=False),
    sa.Column('public_key', sa.Text(), nullable=False),
    sa.Column('sign_count', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_webauthn_credentials_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_webauthn_credentials')),
    sa.UniqueConstraint('credential_id', name=op.f('uq_user_webauthn_credentials_credential_id'))
    )
    op.create_index('idx_user_webauthn_credential', 'user_webauthn_credentials', ['credential_id'], unique=False)
    op.create_index('idx_user_webauthn_user', 'user_webauthn_credentials', ['user_id'], unique=False)
    op.create_table('episodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('show_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.Column('season_number', sa.Integer(), nullable=False),
    sa.Column('episode_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('still_path', sa.String(length=500), nullable=True),
    sa.Column('air_date', sa.Date(), nullable=True),
    sa.Column('runtime', sa.Integer(), nullable=True),
    sa.Column('monitored', sa.Boolean(), nullable=False),
    sa.Column('has_file', sa.Boolean(), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('quality_detected', sa.String(length=50), nullable=True),
    sa.Column('codec', sa.String(length=50), nullable=True),
    sa.Column('resolution', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], name=op.f('fk_episodes_season_id_seasons'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], name=op.f('fk_episodes_show_id_shows'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_episodes')),
    sa.UniqueConstraint('show_id', 'season_number', 'episode_number', name=op.f('uq_episodes_show_id'))
    )
    op.create_index('idx_episodes_has_file', 'episodes', ['has_file'], unique=False)
    op.create_index('idx_episodes_monitored', 'episodes', ['monitored'], unique=False)
    op.create_index('idx_episodes_season', 'episodes', ['season_id'], unique=False)
    op.create_index('idx_episodes_show', 'episodes', ['show_id'], unique=False)
    op.create_table('tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('track_position', sa.Integer(), nullable=True),
    sa.Column('disk_number', sa.Integer(), nullable=True),
    sa.Column('deezer_id', sa.BigInteger(), nullable=True),
    sa.Column('album_id', sa.Integer(), nullable=True),
    sa.Column('isrc', sa.String(length=50), nullable=True),
    sa.Column('explicit_lyrics', sa.Boolean(), nullable=True),
    sa.Column('preview', sa.String(length=500), nullable=True),
    sa.Column('artist_name', sa.String(length=255), nullable=True),
    sa.Column('album_title', sa.String(length=255), nullable=True),
    sa.Column('has_file', sa.Boolean(), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('monitored', sa.Boolean(), nullable=False, server_default='true'),
    sa.Column('upgrade_allowed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], name=op.f('fk_tracks_album_id_albums'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tracks')),
    sa.UniqueConstraint('deezer_id', name=op.f('uq_tracks_deezer_id'))
    )
    op.create_index('idx_tracks_album_id', 'tracks', ['album_id'], unique=False)
    op.create_index('idx_tracks_deezer_id', 'tracks', ['deezer_id'], unique=False)
    op.create_index('idx_tracks_isrc', 'tracks', ['isrc'], unique=False)
    op.create_index('idx_tracks_monitored', 'tracks', ['monitored'], unique=False)
    op.create_table('transcoding_progress',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('frame', sa.Integer(), nullable=True),
    sa.Column('fps', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('bitrate', sa.String(length=50), nullable=True),
    sa.Column('size', sa.BigInteger(), nullable=True),
    sa.Column('time', sa.String(length=50), nullable=True),
    sa.Column('speed', sa.String(length=20), nullable=True),
    sa.Column('progress', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['transcoding_jobs.id'], name=op.f('fk_transcoding_progress_job_id_transcoding_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_id', name=op.f('pk_transcoding_progress'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transcoding_progress')
    op.drop_index('idx_tracks_monitored', table_name='tracks')
    op.drop_index('idx_tracks_isrc', table_name='tracks')
    op.drop_index('idx_tracks_deezer_id', table_name='tracks')
    op.drop_index('idx_tracks_album_id', table_name='tracks')
    op.drop_table('tracks')
    op.drop_index('idx_episodes_show', table_name='episodes')
    op.drop_index('idx_episodes_season', table_name='episodes')
    op.drop_index('idx_episodes_monitored', table_name='episodes')
    op.drop_index('idx_episodes_has_file', table_name='episodes')
    op.drop_table('episodes')
    op.drop_index('idx_user_webauthn_user', table_name='user_webauthn_credentials')
    op.drop_index('idx_user_webauthn_credential', table_name='user_webauthn_credentials')
    op.drop_table('user_webauthn_credentials')
    op.drop_index('idx_user_totp_user', table_name='user_totp')
    op.drop_table('user_totp')
    op.drop_index('idx_user_auth_providers_user', table_name='user_auth_providers')
    op.drop_index('idx_user_auth_providers_type', table_name='user_auth_providers')
    op.drop_index('idx_user_auth_providers_subject', table_name='user_auth_providers')
    op.drop_table('user_auth_providers')
    op.drop_index('idx_transcoding_rules_priority', table_name='transcoding_rules')
    op.drop_index('idx_transcoding_rules_enabled', table_name='transcoding_rules')
    op.drop_table('transcoding_rules')
    op.drop_index('idx_transcoding_jobs_user', table_name='transcoding_jobs')
    op.drop_index('idx_transcoding_jobs_status', table_name='transcoding_jobs')
    op.drop_index('idx_transcoding_jobs_media', table_name='transcoding_jobs')
    op.drop_index('idx_transcoding_jobs_created', table_name='transcoding_jobs')
    op.drop_table('transcoding_jobs')
    op.drop_index('idx_seasons_show', table_name='seasons')
    op.drop_index('idx_seasons_monitored', table_name='seasons')
    op.drop_table('seasons')
    op.drop_index('idx_media_tags_tag', table_name='media_tags')
    op.drop_index('idx_media_tags_media', table_name='media_tags')
    op.drop_table('media_tags')
    op.drop_index('idx_collection_items_media', table_name='collection_items')
    op.drop_index('idx_collection_items_collection', table_name='collection_items')
    op.drop_table('collection_items')
    op.drop_index('idx_anime_episodes_monitored', table_name='anime_episodes')
    op.drop_index('idx_anime_episodes_has_file', table_name='anime_episodes')
    op.drop_index('idx_anime_episodes_anime', table_name='anime_episodes')
    op.drop_table('anime_episodes')
    op.drop_index('idx_albums_status', table_name='albums')
    op.drop_index('idx_albums_monitored', table_name='albums')
    op.drop_index('idx_albums_media_profile_id', table_name='albums')
    op.drop_index('idx_albums_deezer_id', table_name='albums')
    op.drop_index('idx_albums_artist_id', table_name='albums')
    op.drop_table('albums')
    op.drop_index('idx_users_username', table_name='users')
    op.drop_index('idx_users_role', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_transcoding_profiles_name', table_name='transcoding_profiles')
    op.drop_table('transcoding_profiles')
    op.drop_index('idx_tags_name', table_name='tags')
    op.drop_table('tags')
    op.drop_index('idx_shows_tvdb_id', table_name='shows')
    op.drop_index('idx_shows_tmdb_id', table_name='shows')
    op.drop_index('idx_shows_status_monitored', table_name='shows')
    op.drop_index('idx_shows_status', table_name='shows')
    op.drop_index('idx_shows_media_profile_id', table_name='shows')
    op.drop_index('idx_shows_imdb_id', table_name='shows')
    op.drop_table('shows')
    op.drop_index('idx_movies_tmdb_id', table_name='movies')
    op.drop_index('idx_movies_status_monitored', table_name='movies')
    op.drop_index('idx_movies_status', table_name='movies')
    op.drop_index('idx_movies_monitored', table_name='movies')
    op.drop_index('idx_movies_media_profile_id', table_name='movies')
    op.drop_index('idx_movies_imdb_id', table_name='movies')
    op.drop_index('idx_movies_collection', table_name='movies')
    op.drop_table('movies')
    op.drop_index('idx_media_profiles_name', table_name='media_profiles')
    op.drop_table('media_profiles')
    op.drop_index('idx_hardware_accel_type', table_name='hardware_accel_devices')
    op.drop_index('idx_hardware_accel_available', table_name='hardware_accel_devices')
    op.drop_table('hardware_accel_devices')
    op.drop_index('idx_download_history_status', table_name='download_history')
    op.drop_index('idx_download_history_media', table_name='download_history')
    op.drop_index('idx_download_history_hash', table_name='download_history')
    op.drop_table('download_history')
    op.drop_index('idx_download_clients_enabled', table_name='download_clients')
    op.drop_index('idx_download_clients_default', table_name='download_clients')
    op.drop_table('download_clients')
    op.drop_index('idx_collections_tmdb', table_name='collections')
    op.drop_index('idx_collections_name', table_name='collections')
    op.drop_table('collections')
    op.drop_index('idx_blocklist_title', table_name='blocklist')
    op.drop_index('idx_blocklist_media', table_name='blocklist')
    op.drop_table('blocklist')
    op.drop_index('idx_artists_monitored', table_name='artists')
    op.drop_index('idx_artists_deezer_id', table_name='artists')
    op.drop_table('artists')
    op.drop_index('idx_app_settings_key', table_name='app_settings')
    op.drop_index('idx_app_settings_category', table_name='app_settings')
    op.drop_table('app_settings')
    op.drop_index('idx_anime_status_monitored', table_name='anime')
    op.drop_index('idx_anime_status', table_name='anime')
    op.drop_index('idx_anime_media_profile_id', table_name='anime')
    op.drop_index('idx_anime_mal_id', table_name='anime')
    op.drop_index('idx_anime_anilist_id', table_name='anime')
    op.drop_table('anime')
    # ### end Alembic commands ###
